//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int order_id { get; set; }
        public Nullable<int> users_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> order_quantity { get; set; }
        public Nullable<int> fruit_id { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
    
        public virtual fruit fruit { get; set; }
        public virtual user user { get; set; }
    }
}
